---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: simple-pv-hostpath
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/temp"    